name: "Test and release to NPM.JS"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  test:
    name: Run bun test
    runs-on: ubuntu-latest

    env:
      COOKIE: ${{ secrets.COOKIE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: List content
        run: ls -al

  # Not working anymore
  #      - name: Run test
  #        run: bun test --concurrent

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test
    env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish to NPM
        run: bun publish -p --access public
